# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ceaser_cipher_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_caesar_cipher_Info(object):
    def setupUi(self, caesar_cipher_Info):
        caesar_cipher_Info.setObjectName("caesar_cipher_Info")
        caesar_cipher_Info.resize(482, 558)
        caesar_cipher_Info.setStyleSheet("background-color: rgba(34, 44, 58, 1);")
        self.label_2 = QtWidgets.QLabel(caesar_cipher_Info)
        self.label_2.setGeometry(QtCore.QRect(0, 520, 471, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/dlack_balk_line.png"))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(caesar_cipher_Info)
        self.label.setGeometry(QtCore.QRect(130, 0, 201, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(caesar_cipher_Info)
        self.label_3.setGeometry(QtCore.QRect(70, 350, 341, 161))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Images/caesar_cipher_IMAGE.png"))
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(caesar_cipher_Info)
        self.textBrowser.setGeometry(QtCore.QRect(20, 120, 441, 211))
        self.textBrowser.setStyleSheet("background-color: rgb(34, 44, 58);\n"
"border: 0px solid rgb(33, 34, 39);\n"
"border-radius: 5px;")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(caesar_cipher_Info)
        QtCore.QMetaObject.connectSlotsByName(caesar_cipher_Info)

    def retranslateUi(self, caesar_cipher_Info):
        _translate = QtCore.QCoreApplication.translate
        caesar_cipher_Info.setWindowTitle(_translate("caesar_cipher_Info", "Шифр Цезаря"))
        self.label.setText(_translate("caesar_cipher_Info", "Шифр Цезаря"))
        self.textBrowser.setHtml(_translate("caesar_cipher_Info", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ffffff;\">Шифр Цезаря (лат. Notae Caesarianae), также известный как шифр сдвига или код Цезаря — разновидность шифра подстановки, в котором каждый символ в открытом тексте заменяется символом, находящимся на некотором постоянном числе позиций левее или правее него в алфавите (так, в шифре со сдвигом вправо на 3, А была бы заменена на Г, Б станет Д, и так далее. Шифр был назван в честь римского полководца Гая Юлия Цезаря, использовавшего его для секретной переписки со своими военачальниками</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    caesar_cipher_Info = QtWidgets.QDialog()
    ui = Ui_caesar_cipher_Info()
    ui.setupUi(caesar_cipher_Info)
    caesar_cipher_Info.show()
    sys.exit(app.exec_())
