# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'File.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 640)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 640))
        MainWindow.setStyleSheet("QPushButton\n"
"{\n"
"    corlor: white;\n"
"}\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(34, 44, 58, 1);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(650, 290, 421, 231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/Logo_fileWindow.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 600, 1200, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/andre/.designer/backup/Images/dlack_balk_line.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 40, 291, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_Key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Key.setGeometry(QtCore.QRect(140, 180, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Key.setFont(font)
        self.plainTextEdit_Key.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.plainTextEdit_Key.setObjectName("plainTextEdit_Key")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.BackButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.BackButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/BackButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BackButton.setIcon(icon)
        self.BackButton.setIconSize(QtCore.QSize(150, 150))
        self.BackButton.setObjectName("BackButton")
        self.EncriptionMode = QtWidgets.QPushButton(self.centralwidget)
        self.EncriptionMode.setGeometry(QtCore.QRect(720, 90, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.EncriptionMode.setFont(font)
        self.EncriptionMode.setStyleSheet("background-color: rgba(72, 199, 166, 1);\n"
"color: white;\n"
"border-radius: 5px;\n"
"")
        self.EncriptionMode.setObjectName("EncriptionMode")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(140, 150, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.DownloadFile = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadFile.setGeometry(QtCore.QRect(140, 70, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DownloadFile.setFont(font)
        self.DownloadFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DownloadFile.setStyleSheet("background-color: rgba(255, 255, 255, 1);\n"
"color: rgba(126, 126, 126, 1);\n"
"border-radius: 5px;\n"
" border: 3px solid rgba(126, 126, 126, 1);\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.DownloadFile.setObjectName("DownloadFile")
        self.copyKey = QtWidgets.QPushButton(self.centralwidget)
        self.copyKey.setGeometry(QtCore.QRect(390, 180, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.copyKey.setFont(font)
        self.copyKey.setStyleSheet("background-color:rgba(41, 72, 109, 0);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.copyKey.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyKey.setIcon(icon1)
        self.copyKey.setIconSize(QtCore.QSize(25, 25))
        self.copyKey.setObjectName("copyKey")
        self.InfoButton = QtWidgets.QPushButton(self.centralwidget)
        self.InfoButton.setGeometry(QtCore.QRect(1130, 530, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.InfoButton.setFont(font)
        self.InfoButton.setStyleSheet("background-color: rgba(72, 199, 166, 0);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.InfoButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/andre/.designer/backup/Images/InfoIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InfoButton.setIcon(icon2)
        self.InfoButton.setIconSize(QtCore.QSize(50, 50))
        self.InfoButton.setObjectName("InfoButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(720, 50, 171, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.DecriptionMode = QtWidgets.QPushButton(self.centralwidget)
        self.DecriptionMode.setGeometry(QtCore.QRect(720, 180, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.DecriptionMode.setFont(font)
        self.DecriptionMode.setStyleSheet("background-color: rgba(126, 126, 126, 1);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.DecriptionMode.setObjectName("DecriptionMode")
        self.EncriptionGO = QtWidgets.QPushButton(self.centralwidget)
        self.EncriptionGO.setGeometry(QtCore.QRect(140, 260, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.EncriptionGO.setFont(font)
        self.EncriptionGO.setStyleSheet("background-color: rgba(72, 199, 166, 1);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.EncriptionGO.setObjectName("EncriptionGO")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 350, 301, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.SaveFile = QtWidgets.QPushButton(self.centralwidget)
        self.SaveFile.setGeometry(QtCore.QRect(140, 390, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.SaveFile.setFont(font)
        self.SaveFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SaveFile.setStyleSheet("background-color: rgba(255, 255, 255, 1);\n"
"color: rgba(126, 126, 126, 1);\n"
"border-radius: 5px;\n"
" border: 3px solid rgba(126, 126, 126, 1);\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.SaveFile.setObjectName("SaveFile")
        self.label_saveKey = QtWidgets.QLabel(self.centralwidget)
        self.label_saveKey.setGeometry(QtCore.QRect(140, 470, 301, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_saveKey.setFont(font)
        self.label_saveKey.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_saveKey.setObjectName("label_saveKey")
        self.copyKey_2 = QtWidgets.QPushButton(self.centralwidget)
        self.copyKey_2.setGeometry(QtCore.QRect(390, 500, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.copyKey_2.setFont(font)
        self.copyKey_2.setStyleSheet("background-color:rgba(41, 72, 109, 0);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.copyKey_2.setText("")
        self.copyKey_2.setIcon(icon1)
        self.copyKey_2.setIconSize(QtCore.QSize(25, 25))
        self.copyKey_2.setObjectName("copyKey_2")
        self.KeyDublicate = QtWidgets.QTextBrowser(self.centralwidget)
        self.KeyDublicate.setEnabled(True)
        self.KeyDublicate.setGeometry(QtCore.QRect(140, 500, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.KeyDublicate.setFont(font)
        self.KeyDublicate.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.KeyDublicate.setObjectName("KeyDublicate")
        self.KeyDublicate.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.plainTextEdit_Key.raise_()
        self.BackButton.raise_()
        self.EncriptionMode.raise_()
        self.label_10.raise_()
        self.DownloadFile.raise_()
        self.copyKey.raise_()
        self.InfoButton.raise_()
        self.label_4.raise_()
        self.DecriptionMode.raise_()
        self.EncriptionGO.raise_()
        self.label_5.raise_()
        self.SaveFile.raise_()
        self.label_saveKey.raise_()
        self.copyKey_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шифрование сообщений"))
        self.label_3.setText(_translate("MainWindow", "Выберите файл"))
        self.EncriptionMode.setText(_translate("MainWindow", "Шифрование"))
        self.label_10.setText(_translate("MainWindow", "Ключ:"))
        self.DownloadFile.setText(_translate("MainWindow", "Выбрать файл...                                "))
        self.label_4.setText(_translate("MainWindow", "режим работы"))
        self.DecriptionMode.setText(_translate("MainWindow", "Расшифровка"))
        self.EncriptionGO.setText(_translate("MainWindow", "Шифровать"))
        self.label_5.setText(_translate("MainWindow", "Cохраните зашифрованный файл"))
        self.SaveFile.setText(_translate("MainWindow", "Сохраните зашифрованный файл...  "))
        self.label_saveKey.setText(_translate("MainWindow", "Не забудьте сохранить ключ!"))
        self.KeyDublicate.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
