# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'History.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageWindow(object):
    def setupUi(self, ManageWindow):
        ManageWindow.setObjectName("ManageWindow")
        ManageWindow.resize(1200, 638)
        ManageWindow.setStyleSheet("QPushButton\n"
"{\n"
"    corlor: white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(ManageWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(34, 44, 58, 1);")
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(70, 150, 1061, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("border: 2px solid white;\n"
"color: rgb(72, 199, 166);\n"
"\n"
"QListWidget::item:hover\n"
"{\n"
"    show-decoration-selected:5;\n"
"    background:skyblue;\n"
"}\n"
"\n"
"QListWidget::item:selected\n"
"{\n"
"    /*border:0px;*/\n"
"    background:lightgray;\n"
"    padding:0px;\n"
"    margin:0px;\n"
"    color:red;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active\n"
"{\n"
"    border-width:0px;\n"
"    background:lightgreen;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section\n"
"{\n"
"    background-color:#F0F0F0;  /*lightgray*/\n"
"    color:black;\n"
"    padding-left:4px\n"
"    /*border:3px solid red;*/   / * Ширина и цвет линии границы заголовка * /\n"
"    /*border:1px solid gray;*/\n"
"}")
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(34, 44, 58))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(144)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.verticalHeader().setDefaultSectionSize(39)
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.BackButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.BackButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/BackButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BackButton.setIcon(icon)
        self.BackButton.setIconSize(QtCore.QSize(150, 150))
        self.BackButton.setObjectName("BackButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 60, 631, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(880, 10, 251, 131))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Images/Logo_messageWindow.png"))
        self.label_7.setObjectName("label_7")
        self.openHistoryMoment = QtWidgets.QPushButton(self.centralwidget)
        self.openHistoryMoment.setGeometry(QtCore.QRect(410, 580, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.openHistoryMoment.setFont(font)
        self.openHistoryMoment.setStyleSheet("background-color: rgba(72, 199, 166, 1);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.openHistoryMoment.setObjectName("openHistoryMoment")
        ManageWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ManageWindow)
        QtCore.QMetaObject.connectSlotsByName(ManageWindow)

    def retranslateUi(self, ManageWindow):
        _translate = QtCore.QCoreApplication.translate
        ManageWindow.setWindowTitle(_translate("ManageWindow", "ManageWindow"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ManageWindow", "текст слева"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ManageWindow", "текст справа"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ManageWindow", "ключ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ManageWindow", "язык"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ManageWindow", "шифр"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ManageWindow", "действие"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ManageWindow", "время"))
        self.label_6.setText(_translate("ManageWindow", "История шифрований сообщений"))
        self.openHistoryMoment.setText(_translate("ManageWindow", "открыть данную запись"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManageWindow = QtWidgets.QMainWindow()
    ui = Ui_ManageWindow()
    ui.setupUi(ManageWindow)
    ManageWindow.show()
    sys.exit(app.exec_())
