# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 640)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 640))
        MainWindow.setStyleSheet("QPushButton\n"
"{\n"
"    corlor: white;\n"
"}\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(34, 44, 58, 1);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(476, 30, 246, 156))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/Logo_messageWindow.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 600, 1200, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/dlack_balk_line.png"))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit_Left = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Left.setGeometry(QtCore.QRect(150, 160, 271, 271))
        self.plainTextEdit_Left.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.plainTextEdit_Left.setObjectName("plainTextEdit_Left")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 110, 311, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_Right = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Right.setGeometry(QtCore.QRect(770, 160, 271, 271))
        self.plainTextEdit_Right.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.plainTextEdit_Right.setPlainText("")
        self.plainTextEdit_Right.setObjectName("plainTextEdit_Right")
        self.plainTextEdit_Key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Key.setGeometry(QtCore.QRect(150, 480, 265, 41))
        self.plainTextEdit_Key.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.plainTextEdit_Key.setObjectName("plainTextEdit_Key")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(770, 110, 301, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.BackButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.BackButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/BackButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BackButton.setIcon(icon)
        self.BackButton.setIconSize(QtCore.QSize(150, 150))
        self.BackButton.setObjectName("BackButton")
        self.Encription = QtWidgets.QPushButton(self.centralwidget)
        self.Encription.setGeometry(QtCore.QRect(440, 500, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Encription.setFont(font)
        self.Encription.setStyleSheet("background-color: rgba(72, 199, 166, 1);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.Encription.setObjectName("Encription")
        self.change = QtWidgets.QPushButton(self.centralwidget)
        self.change.setGeometry(QtCore.QRect(520, 370, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.change.setFont(font)
        self.change.setStyleSheet("background-color:rgba(41, 72, 109, 1);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.change.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/change.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change.setIcon(icon1)
        self.change.setIconSize(QtCore.QSize(1000, 1000))
        self.change.setObjectName("change")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(70, 480, 71, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.DownloadTxt = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadTxt.setGeometry(QtCore.QRect(150, 390, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DownloadTxt.setFont(font)
        self.DownloadTxt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DownloadTxt.setStyleSheet("background-color: rgba(255, 255, 255, 1);\n"
"color: rgba(126, 126, 126, 1);\n"
"border-radius: 5px;\n"
" border: 3px solid rgba(126, 126, 126, 1);\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.DownloadTxt.setObjectName("DownloadTxt")
        self.language = QtWidgets.QComboBox(self.centralwidget)
        self.language.setGeometry(QtCore.QRect(50, 160, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.language.setFont(font)
        self.language.setStyleSheet("\n"
"#language{\n"
"    color: rgb(33, 34, 39);\n"
"border: 5px solid rgb(33, 34, 39);\n"
"border-radius: 5px;\n"
"background-color: qlineargradient(spread:pad, x1:0.085, y1:1, x2:1, y2:1, stop:0.431818 rgba(255, 255, 255, 255), stop:0.443182 rgba(72, 199, 166, 255));\n"
"padding-left: 6px;\n"
"}\n"
"\n"
"\n"
"#language::drop-down { \n"
"border: Opx;\n"
"}\n"
"\n"
"#language::down-arrow{\n"
"image: url(Images/arrowLang.png);\n"
"width: 25 px;\n"
"height: 25px;\n"
"margin-right: 25px;\n"
"}\n"
"\n"
"/* style for QComboBox after open selcet menu*/\n"
"#language:on {\n"
"border: 5px solid rgb(33, 34, 39);\n"
"}\n"
"\n"
"#language QListView {\n"
"    color: rgb(255, 255, 255);\n"
"font-size: 12px;\n"
"padding: 5px;\n"
"background-color: rgb(41, 72, 109);\n"
"outline: 5px;\n"
"}")
        self.language.setObjectName("language")
        self.language.addItem("")
        self.language.addItem("")
        self.language.addItem("")
        self.code = QtWidgets.QComboBox(self.centralwidget)
        self.code.setGeometry(QtCore.QRect(480, 220, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.code.setFont(font)
        self.code.setStyleSheet("#code{\n"
"    color: rgb(255, 255, 255);\n"
"border: 5px solid rgb(33, 34, 39);\n"
"border-radius: 5px;\n"
"background-color: rgb(33, 34, 39);\n"
"padding-left: 46px;\n"
"}\n"
"\n"
"\n"
"#code::drop-down { \n"
"border: Opx;\n"
"}\n"
"\n"
"#code::down-arrow{\n"
"image: url(Images/3 lines.png);\n"
"width: 25 px;\n"
"height: 25px;\n"
"margin-right: 386px;\n"
"}\n"
"\n"
"/* style for QComboBox after open selcet menu*/\n"
"#code:on {\n"
"\n"
"}\n"
"\n"
"#code QListView {\n"
"    color: rgb(33, 34, 39);\n"
"font-size: 12px;\n"
"padding: 2px;\n"
"background-color: rgb(255, 255, 255);\n"
"outline: 5px;\n"
"border-radius: 5px;\n"
"border: 5px;\n"
"border-bottom-color: rgb(33, 34, 39);\n"
"}")
        self.code.setDuplicatesEnabled(False)
        self.code.setFrame(False)
        self.code.setObjectName("code")
        self.code.addItem("")
        self.code.addItem("")
        self.copyLeftPlainText = QtWidgets.QPushButton(self.centralwidget)
        self.copyLeftPlainText.setGeometry(QtCore.QRect(380, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.copyLeftPlainText.setFont(font)
        self.copyLeftPlainText.setStyleSheet("background-color:rgba(41, 72, 109, 0);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.copyLeftPlainText.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyLeftPlainText.setIcon(icon2)
        self.copyLeftPlainText.setIconSize(QtCore.QSize(25, 25))
        self.copyLeftPlainText.setObjectName("copyLeftPlainText")
        self.copyKey = QtWidgets.QPushButton(self.centralwidget)
        self.copyKey.setGeometry(QtCore.QRect(380, 480, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.copyKey.setFont(font)
        self.copyKey.setStyleSheet("background-color:rgba(41, 72, 109, 0);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.copyKey.setText("")
        self.copyKey.setIcon(icon2)
        self.copyKey.setIconSize(QtCore.QSize(25, 25))
        self.copyKey.setObjectName("copyKey")
        self.copyRightPlainText = QtWidgets.QPushButton(self.centralwidget)
        self.copyRightPlainText.setGeometry(QtCore.QRect(1000, 160, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.copyRightPlainText.setFont(font)
        self.copyRightPlainText.setStyleSheet("background-color:rgba(41, 72, 109, 0);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.copyRightPlainText.setText("")
        self.copyRightPlainText.setIcon(icon2)
        self.copyRightPlainText.setIconSize(QtCore.QSize(25, 25))
        self.copyRightPlainText.setObjectName("copyRightPlainText")
        self.SaveMenu = QtWidgets.QPushButton(self.centralwidget)
        self.SaveMenu.setGeometry(QtCore.QRect(1050, 160, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.SaveMenu.setFont(font)
        self.SaveMenu.setStyleSheet("background-color: rgba(72, 199, 166, 1);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: 5px solid rgb(33, 34, 39);\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}\n"
"\n"
"")
        self.SaveMenu.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/3 lines.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveMenu.setIcon(icon3)
        self.SaveMenu.setIconSize(QtCore.QSize(30, 30))
        self.SaveMenu.setObjectName("SaveMenu")
        self.SaveRight = QtWidgets.QPushButton(self.centralwidget)
        self.SaveRight.setGeometry(QtCore.QRect(1050, 200, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SaveRight.setFont(font)
        self.SaveRight.setStyleSheet("background-color: rgba(72, 199, 166, 1);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.SaveRight.setObjectName("SaveRight")
        self.SaveRightWichKey = QtWidgets.QPushButton(self.centralwidget)
        self.SaveRightWichKey.setGeometry(QtCore.QRect(1050, 240, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SaveRightWichKey.setFont(font)
        self.SaveRightWichKey.setStyleSheet("background-color: rgba(72, 199, 166, 1);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.SaveRightWichKey.setObjectName("SaveRightWichKey")
        self.InfoButton = QtWidgets.QPushButton(self.centralwidget)
        self.InfoButton.setGeometry(QtCore.QRect(1130, 530, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.InfoButton.setFont(font)
        self.InfoButton.setStyleSheet("background-color: rgba(72, 199, 166, 0);\n"
"color: white;\n"
"border-radius: 5px;\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    \n"
"    background-color: rgb(135, 255, 71);\n"
"}")
        self.InfoButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/InfoIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InfoButton.setIcon(icon4)
        self.InfoButton.setIconSize(QtCore.QSize(50, 50))
        self.InfoButton.setObjectName("InfoButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шифрование сообщений"))
        self.label_3.setText(_translate("MainWindow", "Сообщение:"))
        self.label_4.setText(_translate("MainWindow", "Зашифрованное сообщение:"))
        self.Encription.setText(_translate("MainWindow", "Зашифровать"))
        self.label_10.setText(_translate("MainWindow", "ключ:"))
        self.DownloadTxt.setText(_translate("MainWindow", "Выбрать файл txt...                            "))
        self.language.setItemText(0, _translate("MainWindow", "ML"))
        self.language.setItemText(1, _translate("MainWindow", "RU"))
        self.language.setItemText(2, _translate("MainWindow", "EN"))
        self.code.setItemText(0, _translate("MainWindow", "Шифр Цезаря"))
        self.code.setItemText(1, _translate("MainWindow", "Шифр Виженера"))
        self.SaveRight.setText(_translate("MainWindow", "сохранить"))
        self.SaveRightWichKey.setText(_translate("MainWindow", "сохранить с ключем"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
