# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vigenere_cipher_Info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vigenere_cipher_Info(object):
    def setupUi(self, vigenere_cipher_Info):
        vigenere_cipher_Info.setObjectName("vigenere_cipher_Info")
        vigenere_cipher_Info.resize(480, 558)
        vigenere_cipher_Info.setStyleSheet("background-color: rgba(34, 44, 58, 1);")
        self.label_2 = QtWidgets.QLabel(vigenere_cipher_Info)
        self.label_2.setGeometry(QtCore.QRect(0, 520, 481, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/dlack_balk_line.png"))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(vigenere_cipher_Info)
        self.label.setGeometry(QtCore.QRect(110, 20, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(vigenere_cipher_Info)
        self.textBrowser.setGeometry(QtCore.QRect(20, 100, 441, 201))
        self.textBrowser.setStyleSheet("background-color: rgb(34, 44, 58);\n"
"border: 0px solid rgb(33, 34, 39);\n"
"border-radius: 5px;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(vigenere_cipher_Info)
        self.label_3.setGeometry(QtCore.QRect(30, 310, 431, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Images/vigenere_cipher_Im.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(vigenere_cipher_Info)
        QtCore.QMetaObject.connectSlotsByName(vigenere_cipher_Info)

    def retranslateUi(self, vigenere_cipher_Info):
        _translate = QtCore.QCoreApplication.translate
        vigenere_cipher_Info.setWindowTitle(_translate("vigenere_cipher_Info", "Шифр Виженера"))
        self.label.setText(_translate("vigenere_cipher_Info", "Шифр виженера "))
        self.textBrowser.setHtml(_translate("vigenere_cipher_Info", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ffffff;\">Шифр Виженера - это метод шифрования алфавитного текста с использованием серии различных шифров Цезаря, основанных на буквах ключевого слова. Это простая форма полиалфавитной замены. Шифр Виженера (шаблон: IPA-fr) изобретался много раз. Первоначально метод был описан Джованом Баттистой Белласо в его книге 1553 года &quot;Шифра дель&quot;. Sig. Джован Баттиста Белласо; однако позже, в 19 веке, эта схема была ошибочно приписана Блезу де Виженеру и в настоящее время широко известна как &quot;шифр Виженера&quot;.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vigenere_cipher_Info = QtWidgets.QDialog()
    ui = Ui_vigenere_cipher_Info()
    ui.setupUi(vigenere_cipher_Info)
    vigenere_cipher_Info.show()
    sys.exit(app.exec_())
